image: node:19.2.0

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install          
          - npm run build
        artifacts:
          - build/**
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy
            variables:
              USER: $USER
              SERVER: $SERVER
              REMOTE_PATH: '/var/home-page'
              LOCAL_PATH: 'build/*'
              EXTRA_ARGS: ['-P', '1983']             
              SSH_KEY: '$MY_SSH_KEY'