image: node:19.2.0

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install          
          - npm run build
        artifacts:
          - build/**
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:1.4.1
            variables:
              USER: 'root'
              SERVER: 'tubaluga.ru'
              REMOTE_PATH: '/var/home-page/'
              LOCAL_PATH: 'build'
              EXTRA_ARGS: ['-P', '1983']
              DEBUG: 'true'
              SSH_KEY: '$MY_SSH_KEY'